# Generated by Django 2.2.4 on 2019-10-19 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('venue', models.CharField(max_length=1024)),
                ('speakers', models.CharField(max_length=1024)),
                ('details', models.CharField(max_length=30000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
