# Generated by Django 2.2.4 on 2019-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0002_auto_20191019_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('fblink', models.URLField(blank=True, max_length=3000, null=True)),
                ('gitlink', models.URLField(blank=True, max_length=3000, null=True)),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
