# Generated by Django 2.2.4 on 2019-10-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0003_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
