# Generated by Django 2.2.4 on 2020-06-30 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0003_discussion_events_discussion_projects_favorite_events_favorite_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='blogs/')),
                ('topic', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=1024)),
                ('posted_on', models.DateField(default=datetime.date.today)),
                ('details', models.TextField()),
            ],
        ),
    ]
