# Generated by Django 2.2.4 on 2019-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0004_members_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='position',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
