# Generated by Django 2.2.4 on 2019-10-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodingClubIITG', '0007_auto_20191030_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
